[package]
name = "linear_regression"
version = "0.1.0"
edition = "2024"

[dependencies]

burn = { version = "0.17.0", features = ["metal", "train"] }
csv = "1.3.1"
itertools = "0.14.0"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
